# Generated by Django 5.2.3 on 2025-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_clients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
